name: Build CSS # TODO: and deploy to Pressable

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository and enables nodejs
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      
      - name: Install npm dependencies
        run:  npm ci
        
      - name: Compile SCSS
        run: npm run compile:css

      # TODO: deploy the compiled theme to Pressable
